name: Feature Request
description: Suggest a new feature for Juju
labels:
  - kind/feature
  - needs-triage
body:
  - type: textarea
    id: Problem-Description
    attributes:
      label: Problem description
      description: "Describe the problem/use-case: "
      placeholder: ex. "I need to be able to see the local time on each machine."
    validations:
      required: true

  - type: textarea
    id: Desired-Behaviour
    attributes:
      label: Desired behaviour
      description: "Describe the desired behaviour: "
      placeholder: ex. "`juju status` could return the current time reported by each machine."
    validations:
      required: true

  - type: textarea
    id: Info-Notes
    attributes:
      label: "Notes & References"
      description: "Please add relevant notes, other related issues/PRs, anything to help build a solution."
    validations:
      required: false
